export const DROP_SOURCES: Array<{ type: string; name: string; location?: string; drops: string[] }> = [
  {
    type: 'Main Bosses',
    name: 'Knuckle Dragger',
    location: 'Windshear Waste',
    drops: ['Desperado'],
  },
  {
    type: 'Main Bosses',
    name: 'Boom and Bewm',
    location: 'Southern Shelf',
    drops: ['Fuse', 'Payload'],
  },
  {
    type: 'Main Bosses',
    name: 'Captain Flynt',
    location: 'Southern Shelf',
    drops: ['Immolator', 'Flashover'],
  },
  {
    type: 'Main Bosses',
    name: 'Bad Maw',
    location: 'Three Horns - Valley',
    drops: ['Concentration', 'Anubis'],
  },
  {
    type: 'Main Bosses',
    name: 'Wilhelm',
    location: 'End of the Line',
    drops: ['ALT3RN4T0R', 'R3FL3X0R-1340'],
  },
  {
    type: 'Main Bosses',
    name: 'Bloodwing / Son of Mothrakk',
    location: 'Wildlife Exploitation Preserve',
    drops: ['ByrdShot'],
  },
  {
    type: 'Main Bosses',
    name: 'BNK3R',
    location: 'The Bunker',
    drops: ['Exclusion Zone', 'Hyperspace'],
  },
  {
    type: 'Main Bosses',
    name: 'Mortar',
    location: 'Sawtooth Cauldron',
    drops: ['Contagion', 'Rocket Jumper'],
  },
  {
    type: 'Main Bosses',
    name: 'Saturn',
    location: 'Arid Nexus Badlands',
    drops: ['Apollo', 'Galaxy'],
  },
  {
    type: 'Main Bosses',
    name: 'The Warrior',
    location: 'Vault of the Warrior',
    drops: ['Vault Key', 'Myrmidon', 'Wonka', 'Brimstone', 'Bernee'],
  },

  {
    type: 'World/Side Bosses',
    name: 'Southpaw Assassins',
    location: 'Southpaw Steam & Power',
    drops: ['Adaptation', 'Shrapnel', 'Ork Shoota', 'Stormtrooper', 'Bifurcator'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Bag Man',
    location: 'The Holy Spirits',
    drops: ['Surplus', 'Robin'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Black Queen',
    location: 'The Dust',
    drops: ['Starburst', 'Perforator'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Blue',
    location: 'Caustic Caverns',
    drops: ['Moirai'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Boll',
    location: 'Three Horns - Divide',
    drops: ['Moirai'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Bone Head 2.0',
    location: 'Arid Nexus Badlands',
    drops: ['Double Anarchy'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Donkey Mong',
    location: 'Eridium Blight',
    drops: ['Barrel Troll'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Doc Mercy',
    location: 'Three Horns - Valley',
    drops: ['RifRaf', 'Duality'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Flinter',
    location: 'Bloodshot Stronghold',
    drops: [],
  },
  {
    type: 'World/Side Bosses',
    name: 'Foreman',
    location: 'Opportunity',
    drops: ['Liquidation', 'Revectoriser'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Geary',
    location: 'Eridium Blight',
    drops: ['Mythos'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Gettle / Mobley',
    location: 'The Dust',
    drops: ['EMF', 'Saviour'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Henry',
    location: 'The Highlands',
    drops: ['Rolan', 'Clusta'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Hunter Helquist',
    location: 'Arid Nexus Boneyard',
    drops: ['Copyright Infringement'],
  },
  {
    type: 'World/Side Bosses',
    name: 'King Mong',
    location: 'Eridium Blight',
    drops: ['Sovereign'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Laney White',
    location: 'The Fridge',
    drops: ['Butterfly'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Madame Von Bartlesby',
    location: 'Tundra Express',
    drops: ['Swarm'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Mad Mike',
    location: 'Lynchwood',
    drops: ['Tantrum', 'Bastion'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Mad Dog',
    location: 'Lynchwood',
    drops: ['Bastion', 'Tantrum'],
  },
  {
    type: 'World/Side Bosses',
    name: 'McNally',
    location: 'The Dust',
    drops: ['Lead Sprinkler', 'Kneecapper'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Old-Slappy',
    location: 'Highlands Outwash',
    drops: ['SOS Flare'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Pimon / Tumba',
    location: 'Wildlife Exploitation Preserve',
    drops: ['Entropy', 'Last Resort'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Rakkman',
    location: 'The Fridge',
    drops: ['Corroderator'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Savage Lee',
    location: 'Three Horns - Divide',
    drops: ['Shrocket'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Sarcastic Slab',
    location: 'Thousand Cuts',
    drops: ['Celebration'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Sinkhole',
    location: 'The Fridge',
    drops: ['Vortex'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Scorch',
    location: 'Frostburn Canyon',
    drops: ['Unburden'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Smash Head',
    location: 'The Fridge',
    drops: ['Meltdown'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Ug-Thak, Lord of Skags',
    location: 'Wildlife Exploitation Preserve',
    drops: ['Nuclear Proliferation'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Incinerator Clayton',
    location: 'Frostburn Canyon',
    drops: ['Solar Slugger', 'Influencial'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Mick Zaford / Tector & Jimbo',
    location: 'The Dust',
    drops: ['Blackjack', 'High Stakes'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Badass Creeper',
    location: 'Caustic Caverns',
    drops: ['Revectorizer', 'Salvo'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Prospector Zeke',
    location: 'Tundra Express',
    drops: ['Slag Habit', 'Fillet', 'Dynamighty'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Terramilk the Wholy',
    location: 'The Highlands - Overlook',
    drops: ['Sunrise', 'Spilled Milk'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Spycho',
    location: 'Frostburn Canyon',
    drops: ['Circulation'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Moxxi Tipping',
    location: 'Sanctuary',
    drops: ['Enrapture', 'Shock Factor', 'Unicorn', 'Impulse', 'Adobois', 'Blessing'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Dust Boxes',
    location: 'The Dust',
    drops: ['Resourceful'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Lascaux Cave Pool',
    drops: ['Raiju'],
  },
  {
    type: 'World/Side Bosses',
    name: 'Sheriff of Lynchwood / Deputy Winger',
    location: 'Lynchwood',
    drops: ['High Noon', 'Grand Slam', 'Wild Bill', 'T-800'],
  },
  {
    type: 'DLC Bosses',
    name: 'Herle',
    location: 'Washburne Refinery',
    drops: ['Barrel Troll', 'Thermoshock', 'Dispensary'],
  },
  {
    type: 'DLC Bosses',
    name: 'P3RV-E',
    location: 'Washburne Refinery',
    drops: ['ERROR 418'],
  },
  {
    type: 'DLC Bosses',
    name: 'No-Beard',
    location: 'Oasis',
    drops: ['Snake Oil'],
  },
  {
    type: 'DLC Bosses',
    name: 'Grendel / Tinkles',
    location: 'Oasis',
    drops: ['White Tiger', 'Lynceus'],
  },
  {
    type: 'DLC Bosses',
    name: 'Big Sleep',
    location: `Hayter's Folly`,
    drops: ['Hypnofocused', 'Culverin'],
  },
  {
    type: 'DLC Bosses',
    name: 'DJ Tanner',
    location: 'Magnys Lighthouse',
    drops: ['Buzzwords'],
  },
  {
    type: 'DLC Bosses',
    name: 'Sully The Stabber',
    location: 'The Beatdown',
    drops: ['Fillet'],
  },
  {
    type: 'DLC Bosses',
    name: 'Motor Mama',
    location: 'Southern Raceway',
    drops: ['Sweeper'],
  },
  {
    type: 'DLC Bosses',
    name: 'Badassasaurus',
    location: 'Torgue Arena',
    drops: ['B-Rex', "Mr Torgue's Back Muscles"],
  },
  {
    type: 'DLC Bosses',
    name: 'Jackenstein',
    location: 'Terminus',
    drops: ['Revolution'],
  },
  {
    type: 'DLC Bosses',
    name: 'Bloodtail',
    location: `Candlerakk's Crag`,
    drops: ['Blood Pact'],
  },
  {
    type: 'DLC Bosses',
    name: 'Arizona',
    location: `Hunter's Grotto`,
    drops: ['Serpens'],
  },
  {
    type: 'DLC Bosses',
    name: 'Bulstoss',
    location: `Hunter's Grotto`,
    drops: ['Powder Blaster'],
  },
  {
    type: 'DLC Bosses',
    name: 'Rouge',
    location: `Candlerakk's Crag`,
    drops: ['Labyrinthine'],
  },
  {
    type: 'DLC Bosses',
    name: 'Bulwark',
    location: `Hunter's Grotto`,
    drops: ['Communal Health Pool'],
  },
  {
    type: 'DLC Bosses',
    name: 'Mister Boney Pants Guy',
    location: `Unassuming Docks`,
    drops: ["Vault Hunter's Knowledge"],
  },
  {
    type: 'DLC Bosses',
    name: "Sorceror's Daughter",
    location: `Lair of Infinite Agony`,
    drops: ['Pyro Lance', 'Blazing Recurve'],
  },
  {
    type: 'DLC Bosses',
    name: 'Unmotivated Golem',
    location: 'Unassuming Docks',
    drops: ['Salvo'],
  },
  {
    type: 'DLC Bosses',
    name: 'Arguk the Butcher',
    location: 'The Forest',
    drops: ['Siphon', 'Double Anarchy'],
  },
  {
    type: 'DLC Bosses',
    name: 'Gold Golem',
    location: 'Mines of Avarice',
    drops: ['Temptress'],
  },
  {
    type: 'DLC Bosses',
    name: 'Warlord Grug / Slog / Turge',
    location: `Murderlin's Temple`,
    drops: ['Kratos', 'Slurd Wurdz'],
  },
  {
    type: 'DLC Bosses',
    name: 'Wizards',
    location: `Murderlin's Temple`,
    drops: ['Tesla Spike', 'Rain of Hades', 'Fire Bolt', 'Arcane Bolt', 'Crystalixir'],
  },
  {
    type: 'DLC Bosses',
    name: 'Cassius',
    location: `Mt. Scarab Research Center`,
    drops: ['Thorns of Cassius', 'DL-44'],
  },
  {
    type: 'DLC Bosses',
    name: 'Dark Web',
    location: 'DAHL Abandon',
    drops: ['Extinction', 'Cloud Kill'],
  },
  {
    type: 'DLC Bosses',
    name: 'Lt. Bolson, Hoffman, Angvar, Tetra',
    location: 'DAHL Abandon',
    drops: ['Extinction', '@Everyone', 'Hot Topic', 'Elementalist', 'Heaven Piercer', 'Sunrise', 'DL-44'],
  },
  {
    type: 'DLC Bosses',
    name: 'Uranus',
    location: 'Helios Fallen',
    drops: ['Jack of All Trades', 'Bread Basket', 'Rainbow Connection', 'Galaxy', 'Heaven Piercer'],
  },
  {
    type: 'DLC Bosses',
    name: 'Sully the Blacksmith',
    location: 'Hallowed Hollow',
    drops: ['Crux Hammer'],
  },
  {
    type: 'DLC Bosses',
    name: 'Wattlegobbler',
    location: 'Gluttony Gulch',
    drops: ["Hornet's Nest", '@Everyone'],
  },
  {
    type: 'DLC Bosses',
    name: 'Tinder Snowflake',
    location: 'Frost Bottom',
    drops: ['Hopscotch', 'Aurora Borealis'],
  },
  {
    type: 'DLC Bosses',
    name: 'Bridget and Colin Hodunk',
    location: 'Rotgut Distillery',
    drops: ['retsiwT'],
  },
  {
    type: 'DLC Bosses',
    name: 'Sparky Flynt',
    location: 'Wam Bam Island',
    drops: ['Covering Fire'],
  },
  {
    type: 'Raid Bosses',
    name: 'Terra - Non-Specific',
    location: `Terramorphous Peak`,
    drops: ['Tubby/Chubby table x10'],
  },
  {
    type: 'Raid Bosses',
    name: 'Terra - Specific',
    location: `Terramorphous Peak`,
    drops: ["Terra's Raging Inferno", "Terra's Seething Contempt", "Terra's Terrifying Presence", 'Spilled Milk'],
  },
  {
    type: 'Raid Bosses',
    name: 'Verm - Seraph',
    location: `Tundra  Express (Farmhouse), Caustic Caverns, Natural Selection Annex`,
    drops: [],
  },
  {
    type: 'Raid Bosses',
    name: 'Verm - Pearl',
    location: `Tundra  Express (Farmhouse), Caustic Caverns, Natural Selection Annex`,
    drops: [],
  },
  {
    type: 'Raid Bosses',
    name: 'Hyperius - Seraph Guns',
    location: 'Washburne Refinery',
    drops: ['Double Dutch', 'Overallocator', 'Ghoulish Gouger', 'Tetramid', 'Asclepius', 'Hateseeker', 'Arc Flash'],
  },
  {
    type: 'Raid Bosses',
    name: 'Hyperius - Seraph Items',
    location: 'Washburne Refinery',
    drops: ['Frustration', 'Corpsebloom', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Master Gee - Seraph Guns',
    location: `Hayter's Folly`,
    drops: ['Double Dutch', 'Overallocator', 'Ghoulish Gouger', 'Tetramid', 'Asclepius', 'Hateseeker', 'Arc Flash'],
  },
  {
    type: 'Raid Bosses',
    name: 'Master Gee - Seraph Items',
    location: `Hayter's Folly`,
    drops: ['Frustration', 'Corpsebloom', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Pete - Seraph Guns',
    location: `Pyro Pete's Bar`,
    drops: ['Unbridled Rage', 'Last Stand', 'Vexation', 'Damper'],
  },
  {
    type: 'Raid Bosses',
    name: 'Pete - Seraph Items',
    location: `Pyro Pete's Bar`,
    drops: ['Shaped Glass', 'Battallion', 'Scattershot', 'Lazarus Effect', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Vorac - Seraph Guns',
    location: `Candlerakk's Crag`,
    drops: ['Quintessence', 'Cattail', 'Virulence', 'Outerfacer'],
  },
  {
    type: 'Raid Bosses',
    name: 'Vorac - Seraph Items',
    location: `Candlerakk's Crag`,
    drops: ['Topaz Brooch', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Dexi - Seraph Guns',
    location: `Hunter's Grotto`,
    drops: ['Quintessence', 'Cattail', 'Virulence', 'Outerfacer'],
  },
  {
    type: 'Raid Bosses',
    name: 'Dexi - Seraph Items',
    location: `Hunter's Grotto`,
    drops: ['Topaz Brooch', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Dragons - Seraph Guns',
    location: `The Winged Storm`,
    drops: ['Powerpuff', 'Half-Life', 'Infraready', 'Cyber Blaster'],
  },
  {
    type: 'Raid Bosses',
    name: 'Dragons - Seraph Items',
    location: `The Winged Storm`,
    drops: ['Retribution', 'Fortifier', 'Pinpoint', 'Slayer of Seraph COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Son of Craw - Non-Pearls',
    location: `Wam Bam Island`,
    drops: ['Aurora Borealis'],
  },
  {
    type: 'Raid Bosses',
    name: 'Son of Craw - Pearl',
    location: `Wam Bam Island`,
    drops: ['Slayer of Craw COMs'],
  },
  {
    type: 'Raid Bosses',
    name: 'Haderax',
    location: `Writhing Deep`,
    drops: ['Montana', 'My Little Friend'],
  },
  {
    type: 'Raid Bosses',
    name: 'OMGWTH*',
    location: `Digistruct Peak`,
    drops: ['Pearl Loot Table x3'],
  },
  {
    type: 'Missions',
    name: 'Breaking the Bank',
    drops: ['High Stakes'],
  },
  {
    type: 'Missions',
    name: "Claptrps's Birthday Bash",
    drops: ['Confetti'],
  },
  {
    type: 'Missions',
    name: `Mighty Morphin'`,
    drops: ['Injector'],
  },
  {
    type: 'Missions',
    name: 'My First Gun',
    drops: [`Clappytrappy's Xiphos`],
  },
  {
    type: 'Missions',
    name: 'Neither Rain nor Sleet nor Skags',
    drops: ['Fleetfoot'],
  },
  {
    type: 'Missions',
    name: 'New Game',
    drops: ['Friendship Is Magic', 'Sapper'],
  },
  {
    type: 'Missions',
    name: 'Out of Body Experience',
    drops: ['Faraday', 'Scatter Laser'],
  },
  {
    type: 'Missions',
    name: 'Rakkaholics Anonymous',
    drops: ['Slurd Wurdz', 'Moxxi Loot Pool'],
  },
  {
    type: 'Missions',
    name: 'Safe & Sound',
    drops: ['Moxxi Loot Pool', 'Dispensary'],
  },
  {
    type: 'Missions',
    name: 'Shoot Me In The Face',
    drops: ['Headshot'],
  },
  {
    type: 'Missions',
    name: 'The Beard Makes The Man',
    drops: ['Temptress'],
  },
  {
    type: 'Missions',
    name: 'The Good, The Bad & The Mordecai',
    drops: ['Moxxi Loot Pool'],
  },
  {
    type: 'Missions',
    name: 'Walking The Dog',
    drops: ['TNTina', 'Binturong'],
  },
  {
    type: 'Missions',
    name: 'Thrgue World Drops',
    drops: ['Menage a Trois'],
  },
  {
    type: 'Tubby Chubby',
    name: 'Tubby Chubby',
    drops: [
      '4th of July',
      'Overcharger',
      'Heat Beam',
      'Gambit',
      '0PT1C-R4Y',
      'Hive Mind',
      'Aftershock',
      'Boring Gun',
      'Juggernaut',
      'Barrage',
      'Maelstrom',
      'Manhattan Project',
      'Executioner',
      'Adaptive Strategy',
      'Plasma Coil',
      'Grindell',
      'Prism',
      'Lift-Off',
      'Queen Bee',
      'Ohm My God',
      'Proton Flare',
      'P5YCH0-B34M3R',
      'Ray Gun',
      'Robin',
      'Soulrender',
      'Transistor',
      'Transcendence',
      'Urchin',
    ],
  },
  {
    type: 'Tribute',
    name: 'Glasspool',
    location: 'Wurmwater',
    drops: ['Jigowatt'],
  },
  {
    type: 'Tribute',
    name: 'William',
    location: 'Wurmwater',
    drops: ['Snake Oil'],
  },
  {
    type: 'Tribute',
    name: 'Axel',
    location: 'Opportunity',
    drops: ['Liquidation'],
  },
  {
    type: 'Tribute',
    name: 'Rose',
    location: 'Opportunity',
    drops: ['Applicator'],
  },
  {
    type: 'Tribute',
    name: 'Strip',
    location: 'Southern Shelf',
    drops: ['Shrocket'],
  },
  {
    type: 'Tribute',
    name: 'Flay',
    location: 'Southern Shelf',
    drops: ['Bombardment'],
  },
  {
    type: 'Tribute',
    name: 'Bailly',
    location: 'Sawtooth Cauldron',
    drops: ['Contagion'],
  },
  {
    type: 'Tribute',
    name: 'Moretus',
    location: 'Sawtooth Cauldron',
    drops: ['Bastion'],
  },
  {
    type: 'Tribute',
    name: 'Cynder',
    location: 'Frostburn',
    drops: ['Solar Slugger'],
  },
  {
    type: 'Tribute',
    name: 'Fuse',
    location: 'Frostburn',
    drops: ['Malfunction'],
  },
  {
    type: 'Tribute',
    name: 'Annie',
    location: 'Lynchwood',
    drops: ['High Noon'],
  },
  {
    type: 'Tribute',
    name: 'Garret',
    location: 'Lynchwood',
    drops: ['T-800'],
  },
  {
    type: 'Tribute',
    name: 'Fiona',
    location: 'Sanctuary',
    drops: ['AWPertunity'],
  },
  {
    type: 'Tribute',
    name: 'Max',
    location: 'Sanctuary',
    drops: ['Edgerunner'],
  },
];

export const DROP_SOURCES_TYPES = Array.from(new Set(DROP_SOURCES.map((source) => source.type)));
