export const ITEMS = [
  {
    origin: '12 Pounder',
    itemType: 'Launcher',
    name: 'TNTina',
    manufacturer: 'Torgue',
    redText: 'Squishy. Squishy squishy squishy.',
    effect: 'Now a Torgue pistol (yes, I made it a pistol), fires dynamite, greatly increased damage',
    rarity: 'Legendary',
  },
  {
    origin: '1340 Shield',
    itemType: 'Shield',
    name: 'ALT3RN4T0R',
    manufacturer: 'Anshin',
    redText: 'BEST RESISTANCE: SEARCHING',
    effect:
      'Converted to Adaptive shield, talks to you occasionally, provides elemental resistance to last damage received',
    rarity: 'Legendary',
  },
  {
    origin: 'Actualizer',
    itemType: 'SMG',
    name: 'Overallocator',
    manufacturer: 'Hyperion',
    redText: 'What else are we going to do with all this spare budget?',
    effect:
      'While unscoped, adds 1 ammo to the mag when firing, slower fire rate, lower damage. While scoped, normal ammo consumption, increased damage & fire rate',
    rarity: 'Seraph',
  },
  {
    origin: 'Aequitas',
    itemType: 'Shield',
    name: 'Applicator',
    manufacturer: 'Atlas',
    redText: 'The only way to handle pressure is to apply it.',
    effect:
      'Fires laser blasts, +25% DoT chance and +75% DoT damage for every Injector or Applicator equipped in the party.',
    rarity: 'Legendary',
  },
  {
    origin: 'Afterburner',
    itemType: 'Relic',
    name: 'Resourceful',
    manufacturer: 'Eridian',
    redText: '',
    effect: 'Provides health regen, shield recharge rate and ammo regen.',
    rarity: 'Legendary',
  },
  {
    origin: 'Ahab',
    itemType: 'Launcher',
    name: 'Arc Flash',
    manufacturer: 'Maliwan',
    redText: "YOU'RE TALKING TO THE MOST ELECTRIFYING MAN IN COMBAT ENTERTAINMENT!",
    effect: 'Always Shock, fires 3 lightning bolts per shot, increased damage, DoT damage & DoT chance, no self damage',
    rarity: 'Seraph',
  },
  {
    origin: 'Amigo Sincero',
    itemType: 'Sniper Rifle',
    name: 'Hot Topic',
    manufacturer: 'Jakobs',
    redText: "Oooooh, I've got some spicy gossip for youuuuu!",
    effect: 'Fire a fireball that penetrates shields, super slow fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Antagonist',
    itemType: 'Shield',
    name: 'Retribution',
    manufacturer: 'Maliwan',
    redText: 'VINDICATIOOOOOOOON!',
    effect:
      'Deflects all enemy bullets but reduces their damage by 20%, launches Incendiary homing balls at attackers.',
    rarity: 'Seraph',
  },
  {
    origin: 'Antifection',
    itemType: 'Grenade',
    name: 'Bread Basket',
    manufacturer: 'Atlas',
    redText: 'Spread the fire like love!',
    effect: 'Antifection rockets have mini-nuke detonations',
    rarity: 'Legendary',
  },
  {
    origin: 'Avenger',
    itemType: 'SMG',
    name: 'Urchin',
    manufacturer: 'Tediore',
    redText: "Don't touch the spiky bits",
    effect: 'Fires lasers, throw reload has greatly increased projectiles, increased damage, DoT chance & DoT damage',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Baby Maker',
    itemType: 'SMG',
    name: 'Swarm',
    manufacturer: 'Tediore',
    redText: 'Bees? BEES?! BEES!',
    effect: 'Always Corrosive, throw reload spawns 10 Hive bees',
    rarity: 'Legendary',
  },
  {
    origin: 'Bad Touch',
    itemType: 'SMG',
    name: 'Enrapture',
    manufacturer: 'Maliwan',
    redText: 'I was pleasured, and I wanted more.',
    effect: 'Fires an explosive beam, increased damage & mag size, 3 ammo per shot',
    rarity: 'Moxxi',
  },
  {
    origin: 'Badaboom',
    itemType: 'Launcher',
    name: 'Rocket Jumper',
    manufacturer: 'S&S Munitions',
    redText: 'Gravity! Noooo!',
    effect:
      '1 mag size, 1 damage, 12 rockets per shot, infinite ammo (Infinity style), fixed parts, always explosive, double accessory (fire rate & swap speed), designed as a mobility tool',
    rarity: 'Legendary',
  },
  {
    origin: 'Bane',
    itemType: 'SMG',
    name: 'Galaxy',
    manufacturer: 'Hyperion',
    redText: 'Simply out of this world...',
    effect: 'Fires 2 orbiting plasma caster projectiles per shot, increased ammo, damage & accuracy',
    rarity: 'Legendary',
  },
  {
    origin: 'Basic Repeater',
    itemType: 'Pistol',
    name: "Clappytrappy's Xiphos",
    manufacturer: 'Atlas',
    redText: '',
    effect: 'Now Vladof, Jakobs barrel, Effervescent rarity',
    rarity: 'Legendary',
  },
  {
    origin: 'Bearcat',
    itemType: 'Assault Rifle',
    name: 'Soulrender',
    manufacturer: 'Dahl',
    redText: 'Picture a soul. Now REND that thing!',
    effect: 'Always non-elemental, fires homing skulls that deal Shock damage.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Bee',
    itemType: 'Shield',
    name: 'Butterfly',
    manufacturer: 'Hyperion',
    redText: '...sting like a bee?',
    effect: 'Reverse Bee shield. When fully depleted, all shots deal bonus Amp Damage.',
    rarity: 'Legendary',
  },
  {
    origin: 'Bekah ',
    itemType: 'Assault Rifle',
    name: 'ERROR 418',
    manufacturer: 'Jakobs',
    redText: 'Wait...am I missing a bracket somewhere?',
    effect:
      'Drops as White Rarity, bullets deal wrong Adaptive damage (Shock on Flesh, Corrosive on Shields, Fire on Flesh)',
    rarity: 'Legendary',
  },
  {
    origin: 'Big Boom Blaster',
    itemType: 'Shield',
    name: 'Unbridled Rage',
    manufacturer: 'Dahl',
    redText: "You wouldn't like me when I'm angry.",
    effect: "When damaged, has a chance to drop a 'Rage Booster' that increases gun damage for a limited time.",
    rarity: 'Seraph',
  },
  {
    origin: 'Bitch',
    itemType: 'SMG',
    name: 'Copyright Infringement',
    manufacturer: 'Hyperion',
    redText: 'Intellectual property has the shelf life of a banana',
    effect: 'Fires Torgue gyrojets, increased accuracy, always non-elemental',
    rarity: 'Legendary',
  },
  {
    origin: 'Black Hole',
    itemType: 'Shield',
    name: 'Thermoshock',
    manufacturer: 'Maliwan',
    redText: 'A sudden surge shifts the tide of battle.',
    effect: 'Releases a Shock singularity nova when depleted, then an Incendiary nova a few seconds later.',
    rarity: 'Legendary',
  },
  {
    origin: 'Blockade',
    itemType: 'Shield',
    name: 'Fortifier',
    manufacturer: 'Pangolin',
    redText: 'Shields are for the weak!',
    effect: 'While your shields are down, provides 50% damage resistance, increased shield recharge delay',
    rarity: 'Seraph',
  },
  {
    origin: 'Blockhead',
    itemType: 'Shotgun',
    name: 'Solar Slugger',
    manufacturer: 'Tediore',
    redText: "You're laughing... The second sun is exploding in minutes and you're laughing...",
    effect: 'Always fire, fires a modified splatgun ball, increased damage, DoT chance & DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Blood of Terramorphous',
    itemType: 'Relic',
    name: "Terra's Seething Contempt",
    manufacturer: 'Eridian',
    redText: 'His contempt was ever growing...',
    effect: 'Provides health regeneration, damage resistance & status damage resistance.',
    rarity: 'Legendary',
  },
  {
    origin: 'Blood of the Seraphs',
    itemType: 'Relic',
    name: 'Corpsebloom',
    manufacturer: 'Eridian',
    redText: 'The flowers have fully bloomed and the body is as good as new.',
    effect: 'Grants health regeneration. The lower your health, the greater the regeneration.',
    rarity: 'Seraph',
  },
  {
    origin: 'Bone Shredder',
    itemType: 'SMG',
    name: 'Saviour',
    manufacturer: 'S&S Munitions',
    redText: 'Hallelujah!',
    effect: 'Increased damage & DoT damage, provides passive ammo regen',
    rarity: 'Legendary',
  },
  {
    origin: 'Bonus Package',
    itemType: 'Grenade',
    name: 'Shrapnel',
    manufacturer: 'Torgue',
    redText: 'Any day we create that much shrapnel is a good day.',
    effect: 'Spawns a LOT of child grenades.',
    rarity: 'Legendary',
  },
  {
    origin: 'Boom Puppy',
    itemType: 'Assault Rifle',
    name: 'Binturong',
    manufacturer: 'Torgue',
    redText: 'I love the smell of pop pop pop pop pop popcorn in the morning.',
    effect: 'Fires 3 grenades for 3 ammo that explode when they bounce. Increased damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Bouncing Bonny',
    itemType: 'Grenade',
    name: 'Revectoriser',
    manufacturer: 'Dahl',
    redText: 'Up, up and away!',
    effect: 'Grenade jumping effect. Minimal base damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Breath of Terramorphous',
    itemType: 'Grenade',
    name: "Terra's Raging Inferno",
    manufacturer: 'Atlas',
    redText: 'His vengeance was firey...',
    effect: 'On detonation, fires a singularity, Fire Bee spurts & BoT flame spurts.',
    rarity: 'Legendary',
  },
  {
    origin: 'Breath of the Seraphs',
    itemType: 'Relic',
    name: 'Topaz Brooch',
    manufacturer: 'Eridian',
    redText: 'Pin it to your body and the software inside will map your extents.',
    effect:
      'Killing an enemy grants increased maximum health, health regeneration, maximum shield capacity & shield recharge rate for a short period of time.',
    rarity: 'Seraph',
  },
  {
    origin: 'Buffalo',
    itemType: 'Sniper Rifle',
    name: 'Enfield',
    manufacturer: 'Jakobs',
    redText: "Don't be a damned ammunition wagon. Be a rifle!",
    effect: 'Increased damage & fire rate, +50% critical damage & +15% movement speed while held',
    rarity: 'Legendary',
  },
  {
    origin: 'Bunny',
    itemType: 'Launcher',
    name: 'Aurora Borealis',
    manufacturer: 'Tediore',
    redText:
      'AT THIS TIME OF YEAR, AT THIS TIME OF DAY, IN THIS PART OF THE COUNTRY, LOCALIZED ENTIRELY WITHIN YOUR KITCHEN!?',
    effect:
      'Fires a snowball that deals splash damage, throw reload launches a cryo ball that spawns an ice storm (AIM UP WHEN THROWING)',
    rarity: 'Legendary',
  },
  {
    origin: 'Butcher',
    itemType: 'Shotgun',
    name: 'Surplus',
    manufacturer: 'Hyperion',
    redText: "If you find yourself in a fair fight, you didn't plan your mission properly",
    effect: 'Increased pellet count & fire rate, Butcher ammo regen, shotgun ammo reserve regen',
    rarity: 'Legendary',
  },
  {
    origin: 'Carnage ',
    itemType: 'Shotgun',
    name: 'Boring Gun',
    manufacturer: 'Torgue',
    redText: 'This is beyond science.',
    effect: "Fires 3 grounded buzzsaws (recreation of BL3's Boring Gun)",
    rarity: 'Legendary',
  },
  {
    origin: 'Chain Lightning',
    itemType: 'Grenade',
    name: 'Tesla Spike',
    manufacturer: 'Maliwan',
    redText: 'Tesla Spikes! Available only at GrummelNet!',
    effect: 'Throws a Storm Front tesla child, 0 grenade cost',
    rarity: 'Legendary',
  },
  {
    origin: 'Chere-amie',
    itemType: 'Sniper Rifle',
    name: '0PT1C-R4Y',
    manufacturer: 'Maliwan',
    redText: 'TARGET: ACQUIRED. PROTOCOL: KILL.',
    effect:
      'Always slag, fires a railgun shot that explodes on impact, deals slag damage and adaptive damage (Fire on flesh, Corrosion on armour, Shock on shields)',
    rarity: 'Legendary',
  },
  {
    origin: 'CHOPPER',
    itemType: 'Assault Rifle',
    name: 'Covering Fire',
    manufacturer: 'S&S Munitions',
    redText: 'JUST! KEEP! SHOOTING!',
    effect: 'Infinite ammo, firing adds bullets to reserve, but reserve drains faster than normal S&S',
    rarity: 'Legendary',
  },
  {
    origin: 'Chulainn',
    itemType: 'SMG',
    name: 'Immolator',
    manufacturer: 'Maliwan',
    redText: 'Burning glory!',
    effect: 'Shoots Minecraft fire bullets, deals fire & slag damage, has a chance to ignite the player',
    rarity: 'Legendary',
  },
  {
    origin: 'Cobra ',
    itemType: 'Sniper Rifle',
    name: 'Manhattan Project',
    manufacturer: 'Jakobs',
    redText: 'The people of this world must unite or they will perish.',
    effect:
      'Costs 5 ammo per shot, fires a bullet that explodes like a nuke, massive damage radius, greatly increased explosion damage, classed as Rocket damage (for rocket damage buffs)',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Commerce',
    itemType: 'SMG',
    name: 'Stormtrooper',
    manufacturer: 'Hyperion',
    redText: 'These are not the droids you are looking for.',
    effect: 'Fires lasers, 75% chance to ignore shields, unlocked elements',
    rarity: 'Legendary',
  },
  {
    origin: 'Conference Call',
    itemType: 'Shotgun',
    name: 'Circulation',
    manufacturer: 'Hyperion',
    redText: 'The circulation of confidence is better than the circulation of money.',
    effect: 'Fires 2 projectiles per shot, bullets release lasers in a spiral motion as they fly.',
    rarity: 'Legendary',
  },
  {
    origin: 'Contraband Sky Rocket',
    itemType: 'Grenade',
    name: 'Oppenheimer',
    manufacturer: 'S&S Munitions',
    redText: 'Now I am become Death, the destroyer of worlds',
    effect: 'Launches 5 nukes on aerial detonation',
    rarity: 'Legendary',
  },
  {
    origin: 'Cracked Sash',
    itemType: 'Shield',
    name: 'Overcharger',
    manufacturer: 'Tediore',
    redText: '',
    effect: '0 recharge delay (always charging)',
    rarity: 'Very Rare',
  },
  {
    origin: 'Cradle',
    itemType: 'Shield',
    name: 'Sweeper',
    manufacturer: 'S&S Munitions',
    redText: 'Always gotta look out for the low kicks.',
    effect: 'When depleted, shoots 3 grounded buzzsaws',
    rarity: 'Legendary',
  },
  {
    origin: 'Creamer',
    itemType: 'Launcher',
    name: 'Barrel Troll',
    manufacturer: 'Torgue',
    redText: 'Brought to you by the good folks at Feenix University!',
    effect: 'Fires a explosive barrel with a high arc (DO NOT USE THIS INDOORS! YOU HAVE BEEN WARNED!)',
    rarity: 'Legendary',
  },
  {
    origin: 'Crit',
    itemType: 'SMG',
    name: 'Siphon',
    manufacturer: 'Maliwan',
    redText: 'Compromise always ends the same.',
    effect:
      'Constantly drains Shields & Health while held. While Shields are empty, provides increased life leech, 5 ricochets, fire rate & projectile speed.',
    rarity: 'Legendary',
  },
  {
    origin: 'Crossfire',
    itemType: 'Grenade',
    name: 'Battallion',
    manufacturer: 'S&S Munitions',
    redText: 'Rally the troops!',
    effect:
      'Explodes a singularity, then launches a Bouncing Betty grenade that releases child grenades while bouncing.',
    rarity: 'Seraph',
  },
  {
    origin: 'Dahlminator',
    itemType: 'Pistol',
    name: 'Ray Gun',
    manufacturer: 'Dahl',
    redText: "REVIVE ME! I'VE GOT RAY GUN!",
    effect: 'Always Corrosive, fires a laser that explodes on impact, energy explosion',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Damned Cowboy',
    itemType: 'Assault Rifle',
    name: 'Powder Blaster',
    manufacturer: 'Jakobs',
    redText: "Give me a keg, and I'll give you a blast.",
    effect: 'Fires 4 explosive bullets per shot, increased fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Deadly Bloom',
    itemType: 'Shield',
    name: 'Nuclear Proliferation',
    manufacturer: 'Torgue',
    redText: 'A nuclear war must never be waged - because a nuclear war can never be one.',
    effect: 'On shield break or death, releases a powerful nuclear explosion',
    rarity: 'Legendary',
  },
  {
    origin: 'Deliverance',
    itemType: 'Shotgun',
    name: 'Bifurcator',
    manufacturer: 'Tediore',
    redText: 'Split it right down the middle',
    effect: 'Fixed parts, always non-elemental, throw reload throws gun like a tomahawk, no explosion',
    rarity: 'Legendary',
  },
  {
    origin: "Deputy's Badge",
    itemType: 'Relic',
    name: 'T-800',
    manufacturer: 'Eridian',
    redText: 'Hasta la vista, baby!',
    effect: 'Increased shotgun fire rate & damage, increased max health, provides passive ammo regeneration',
    rarity: 'Legendary',
  },
  {
    origin: 'Devastator',
    itemType: 'Pistol',
    name: 'Double Dutch',
    manufacturer: 'Torgue',
    redText: 'But no, we cross, crisscross, and recross our old tracks like figure skaters.',
    effect:
      'Fires 4 pellets in a + then X shape, explodes in air or on impact. Seraph Bonus: Increased damage by amount of carried Seraph Crystals',
    rarity: 'Seraph',
  },
  {
    origin: 'Dog',
    itemType: 'Shotgun',
    name: 'Bernee',
    manufacturer: 'S&S Munitions',
    redText: 'Second helpings! Sloppy globs! And melting meat in my mouth!',
    effect: 'Fires splatball pellets, always fire, reduced pellet count, increased damage, DoT damage & DoT chance',
    rarity: 'Legendary',
  },
  {
    origin: 'Easy Mode',
    itemType: 'Shield',
    name: 'Hive Mind',
    manufacturer: 'Hyperion',
    redText: 'Buzz buzz!',
    effect: 'While the Queen Bee is equipped with the Hive Mind, it consumes no ammo.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Electric Chair',
    itemType: 'Grenade',
    name: 'Jack of All Trades',
    manufacturer: 'Atlas',
    redText: 'Master of the "Eh, fuck it" method.',
    effect: 'Payload acts like all base game grenade detonations at once.',
    rarity: 'Legendary',
  },
  {
    origin: 'Elephant Gun',
    itemType: 'Sniper Rifle',
    name: 'Salvo',
    manufacturer: 'Atlas',
    redText: 'Unloaded with great haste!',
    effect: 'Now an Atlas launcher, greatly increased fire rate but reduced damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Emperor',
    itemType: 'SMG',
    name: 'Vector',
    manufacturer: 'Dahl',
    redText: "That's me, because I commit crimes with both direction and magnitude.",
    effect: 'Super high fire rate, lowered accuracy, shoots entire magazine while scoped',
    rarity: 'Legendary',
  },
  {
    origin: 'Evil Smasher',
    itemType: 'Assault Rifle',
    name: 'Bastion',
    manufacturer: 'Torgue',
    redText: 'Have you all seen what this guy can do?',
    effect:
      'On reload, has a 7% chance to enter "Fortified" mode. Fortified Mode decreases movement speed, increases max HP, damage & fire rate, and provides flat damage resistance until next reload or if a menu is entered.',
    rarity: 'Legendary',
  },
  {
    origin: 'Evolution',
    itemType: 'Shield',
    name: 'Frustration',
    manufacturer: 'Anshin',
    redText: 'AAARGH! WHY DO YOU HAVE TO KEEP SHOOTING ME?!',
    effect:
      'Increased shield recharge rate & delay, while damaged but not depleted, grants +3 projectile per shot and greatly increased projectile speed.',
    rarity: 'Seraph',
  },
  {
    origin: 'Fabled Tortoise',
    itemType: 'Shield',
    name: 'Robin',
    manufacturer: 'Pangolin',
    redText: 'When danger reared its ugly head, he bravely turned his tail and fled.',
    effect:
      'Provides passive health regen, movement speed & max health reduced while shield is active. Passive health regen, movement speed & max health increased while shield is depleted',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Fastball',
    itemType: 'Grenade',
    name: 'Last Resort',
    manufacturer: 'Tediore',
    redText: 'Cut my life into pieces!',
    effect: 'On impact, explodes like a nuke',
    rarity: 'Legendary',
  },
  {
    origin: 'Fibber',
    itemType: 'Pistol',
    name: 'Mythos',
    manufacturer: 'Atlas',
    redText: 'May I rise above Mount Olympus!',
    effect:
      'Fires a plasma caster projectile that changes wave type depending on barrel (wavy for Acheron, circular for Atlas, "Octo" for Helix). Acheron reduces health but increases movement speed, Atlas increases health but reduces movement speed, Helix grants life steal',
    rarity: 'Legendary',
  },
  {
    origin: 'Fire Bee',
    itemType: 'Grenade',
    name: 'Brimstone',
    manufacturer: 'Atlas',
    redText: 'Upon the wicked he shall rain snares, fire and brimstone, and a horrible tempest',
    effect: 'Shoots flame spurts in the surrounding area',
    rarity: 'Legendary',
  },
  {
    origin: 'Fire Storm',
    itemType: 'Grenade',
    name: 'Rain of Hades',
    manufacturer: 'Maliwan',
    redText: 'I cast fire & brimstone on your entire lineage!',
    effect: 'On impact, rains down a lot of fireballs.',
    rarity: 'Legendary',
  },
  {
    origin: 'Fireball',
    itemType: 'Grenade',
    name: 'Fire Bolt',
    manufacturer: 'Maliwan',
    redText: 'Thank GOD for cantrips!',
    effect: '0 ammo cost, throws a lobbed fireball with larger splash damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Flakker',
    itemType: 'Shotgun',
    name: 'Lift-Off',
    manufacturer: 'Torgue',
    redText: "Maybe it's your time to lift off and fly. You won't know if you never try.",
    effect: 'Shoots a Flame Spurt grenade that lights the surrounding area on fire... also launches the player.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Flame of the Firehawk',
    itemType: 'Shield',
    name: 'Influencial',
    manufacturer: 'Maliwan',
    redText: "Use code 'SLAG' on checkout for 10% off your first order.",
    effect: 'Releases a Shock nova on break, continually releases Slag Novas while depleted',
    rarity: 'Legendary',
  },
  {
    origin: 'Florentine',
    itemType: 'SMG',
    name: 'Powerpuff',
    manufacturer: 'Maliwan',
    redText: 'Sugar, spice & murderous psychos!',
    effect: 'Fires 3 bullets per 3 ammo, deals fire, shock & corrosive damage',
    rarity: 'Seraph',
  },
  {
    origin: "Fremington's Edge",
    itemType: 'Sniper Rifle',
    name: 'High Stakes',
    manufacturer: 'Hyperion',
    redText: 'The higher the stakes, the more responsible we have to be.',
    effect: 'Element unlocked, has a super low status chance, but super high status damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Fuster Cluck',
    itemType: 'Grenade',
    name: 'Dispensary',
    manufacturer: 'S&S Munitions',
    redText: "They don't stop coming...",
    effect: 'Spawns a LOT of child grenades. Recommended to throw high (or straight up)',
    rarity: 'Legendary',
  },
  {
    origin: 'Godfinger ',
    itemType: 'Sniper Rifle',
    name: 'Revolution',
    manufacturer: 'Atlas',
    redText: 'Better to die fighting for freedom than to be a prisoner all the days of your life.',
    effect: 'Now Atlas, fires a projectile that stops in the air and fires rotating lasers that expand over time',
    rarity: 'Legendary',
  },
  {
    origin: 'Good Touch',
    itemType: 'SMG',
    name: 'Shock Factor',
    manufacturer: 'Maliwan',
    redText: 'Now with guaranteed electrifying results!',
    effect: 'Fires an electrocution beam that hits 10 times per shot, slow fire rate, always Shock',
    rarity: 'Moxxi',
  },
  {
    origin: 'Greed',
    itemType: 'Pistol',
    name: 'Snake Oil',
    manufacturer: 'Jakobs',
    redText: "This is a genuine Jakob's product",
    effect: 'Unlocked elements, always spawns with an element, increased damage, DoT chance & DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Grog Nozzle',
    itemType: 'Pistol',
    name: 'Temptress',
    manufacturer: 'Maliwan',
    redText: "Why don't you come a little closer, sugar?",
    effect:
      'Always Fire, deals explosive & fire damage on impact, 1 ricochet, every 5 seconds, has a 13% chance to make the user "Charming". Charming grants +1 projectile, +3 ricochets, -1 shot cost, increased damage, fire rate & reload speed',
    rarity: 'Moxxi',
  },
  {
    origin: 'Gub',
    itemType: 'Pistol',
    name: 'Ork Shoota',
    manufacturer: 'S&S Munitions',
    redText: 'MOAR DAKKA!',
    effect: 'Fires 3 explosive rounds, always non-elemental (for explosive impact),  decreased accuracy',
    rarity: 'Legendary',
  },
  {
    origin: 'Gunerang',
    itemType: 'Pistol',
    name: 'Confetti',
    manufacturer: 'Tediore',
    redText: 'Add a little confetti to each day',
    effect: 'Throw reload launches a firework projectile, damage scaled on mag size',
    rarity: 'Legendary',
  },
  {
    origin: "Gwen's Head",
    itemType: 'Pistol',
    name: 'Fleetfoot',
    manufacturer: 'Dahl',
    redText: "They weren't smart, but like the Energizer Bunny, they kept going and going.",
    effect: 'Faster movement speed, higher jump height, reduced max HP, unlocked elements, no crit bonus',
    rarity: 'Legendary',
  },
  {
    origin: 'Hail',
    itemType: 'Assault Rifle',
    name: 'Starburst',
    manufacturer: 'Atlas',
    redText: 'The sky was full of stars, and every star an exploding psycho',
    effect: 'Fires a blue wavy projectile that splits into 5 yellow wavy projectiles in flight',
    rarity: 'Legendary',
  },
  {
    origin: 'Hammer Buster',
    itemType: 'Assault Rifle',
    name: 'AWPertunity',
    manufacturer: 'Dahl',
    redText: 'From a place you will not see comes a sound you will not hear.',
    effect: 'Now Dahl, 5 ammo in mag, greatly increased damage & critical damage, decreased fire rate.',
    rarity: 'Legendary',
  },
  {
    origin: 'Hard Carry',
    itemType: 'Relic',
    name: 'Juggernaut',
    manufacturer: 'Eridian',
    redText: "I'm the Juggernaut! Ain't nothin' -- ain't nobody -- can beat me!",
    effect:
      'Increases Gun Damage and Melee Damage. Additionally, increases Fight For Your Life Time and Maximum Health while in the Raid on Digistruct Peak.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Hawkeye',
    itemType: 'Sniper Rifle',
    name: 'Cattail',
    manufacturer: 'Jakobs',
    redText: '"Woof!" says Cattail. "Woof woof woof! Does this confuse you?"',
    effect: 'Fires homing Spiker spikes that explode on impact, increased damage',
    rarity: 'Seraph',
  },
  {
    origin: 'Heart Breaker',
    itemType: 'Shotgun',
    name: 'Adaptive Strategy',
    manufacturer: 'Hyperion',
    redText: 'Improvise. Adapt. Overcome.',
    effect:
      'Adaptive shotgun, 1 ricochet, changes its damage type based on target (fire for flesh, shock for shields, corrosive for armour)',
    rarity: 'Legendary',
  },
  {
    origin: "Hector's Paradise",
    itemType: 'Pistol',
    name: 'DL-44',
    manufacturer: 'Jakobs',
    redText: 'I definitely shot first.',
    effect: 'Now Jakobs Etech, fires lasers, increased base damage & crit damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Hellfire',
    itemType: 'SMG',
    name: 'Heat Beam',
    manufacturer: 'Maliwan',
    redText: 'Roll a Dexterity saving throw or take 1d10 fire damage.',
    effect: 'Fires a fire beam.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Hide of Terramorphous',
    itemType: 'Shield',
    name: "Terra's Terrifying Presence",
    manufacturer: 'S&S Munitions',
    redText: 'His presence makes idolators cower...',
    effect:
      'Combines an Explosive Spike, Slag Nova & Roid shield. Melee attackers get hit with an Explosive flinching spike, when depleted releases a Slag Nova, melee attacks deal additional Roid Damage. Additionally, nearby enemies have slower fire rate, reload speed, projectile speed & movement speed while depleted.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Hive',
    itemType: 'Launcher',
    name: 'Kneecapper',
    manufacturer: 'S&S Munitions',
    redText: 'Say goodbye to ya kneecaps, chucklehead!',
    effect: 'Fires an emitting ball that shoots 5 buzzsaws every 0.5 seconds for 10 seconds',
    rarity: 'Legendary',
  },
  {
    origin: 'Hoplite',
    itemType: 'Shield',
    name: 'Last Stand',
    manufacturer: 'Pangolin',
    redText:
      "Right now, you're the only thing standing between this city - hell, the whole planet - and Handsome Jack's army.",
    effect:
      'Extremely high capacity shield, basically no recharge rate & extremely long recharge delay. Lengths listed on item card',
    rarity: 'Seraph',
  },
  {
    origin: 'Hornet',
    itemType: 'Pistol',
    name: 'Entropy',
    manufacturer: 'Maliwan',
    redText: 'Only entropy comes easy.',
    effect:
      'Now Maliwan, always "NE", fires black holes that deal damage to nearby enemies, damage type changes depending on what character you are playing',
    rarity: 'Legendary',
  },
  {
    origin: 'Hot Mama',
    itemType: 'Sniper Rifle',
    name: 'Sunrise',
    manufacturer: 'Jakobs',
    redText: 'The early bird gets the worm.',
    effect: 'Unlocked elements, always elemental, fires a slow projectile that ricochets into lots of railgun shots.',
    rarity: 'Legendary',
  },
  {
    origin: 'Hydra',
    itemType: 'Shotgun',
    name: 'Serpens',
    manufacturer: 'S&S Munitions',
    redText: 'Poison in your veins',
    effect:
      'Now a Bandit AR (yes, I made it an AR), always Corrosive, fires slithering bullets, increased DoT damage & DoT chance',
    rarity: 'Legendary',
  },
  {
    origin: 'Impaler',
    itemType: 'Shield',
    name: 'Discharger',
    manufacturer: 'Maliwan',
    redText: 'Just let it all out...',
    effect: 'Shock Impaler',
    rarity: 'Legendary',
  },
  {
    origin: 'Infection',
    itemType: 'Pistol',
    name: 'Virulence',
    manufacturer: 'Maliwan',
    redText: "Once you get the bug, then it's on you.",
    effect: 'Fires corrosive fanboat grenades, greatly increased DoT damage & DoT chance',
    rarity: 'Seraph',
  },
  {
    origin: 'Infection Cleaner',
    itemType: 'SMG',
    name: 'Spilled Milk',
    manufacturer: 'Tediore',
    redText: 'My real spirit animal is a goldfish.',
    effect: 'No longer Effervescent, normal SMG, throw reload throws a bone with scaled damage at enemies',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Infinity',
    itemType: 'Pistol',
    name: 'Corroderator',
    manufacturer: 'Dahl',
    redText: "I haven't seen anything like that except, uh, molecular acid.",
    effect:
      'Fires E-tech launcher shots, always Corrosive, increased damage, greatly increased DoT chance & DoT damage, regular mag size & shot cost (1)',
    rarity: 'Legendary',
  },
  {
    origin: 'Interfacer',
    itemType: 'Shotgun',
    name: 'Outerfacer',
    manufacturer: 'Hyperion',
    redText: 'Developer tested, Milk approved!',
    effect: "Vertical Interfacer, pellets don't detonate mid-flight, increased crit damage",
    rarity: 'Seraph',
  },
  {
    origin: 'Invader',
    itemType: 'Sniper Rifle',
    name: 'Perforator',
    manufacturer: 'Hyperion',
    redText: 'To tear and consume, taking for only themselves until there is nothing left',
    effect:
      'Buffed Invader, while scoped, burst fire 5 shots, penetrates shields & provides damage resistance, increased base damage & mag size',
    rarity: 'Legendary',
  },
  {
    origin: 'Jolly Roger',
    itemType: 'Shotgun',
    name: 'Crux Hammer',
    manufacturer: 'S&S Munitions',
    redText: 'Cross their hearts, drop the hammer!',
    effect:
      'Combo of Crux & Hammer from BL1. Always Corrosive, increased damage, DoT damage & DoT chance. Shots explode corrosive & explosive damage on impact.',
    rarity: 'Legendary',
  },
  {
    origin: 'Judge',
    itemType: 'Pistol',
    name: 'Desperado',
    manufacturer: 'Jakobs',
    redText: "It's a long ride to the next town.",
    effect: 'Bullets ricochet 3 times, splits into 3 projectiles on ricochet, increased crit damage',
    rarity: 'Legendary',
  },
  {
    origin: 'KerBlaster',
    itemType: 'Assault Rifle',
    name: 'Ohm My God',
    manufacturer: 'Torgue',
    redText: 'Resistance is futile!',
    effect:
      'Costs 2 ammo per shot, always Shock, fires a shock rocket that launches a Storm Front tesla coil on impact, increased damage & mag size',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Kiss of Death',
    itemType: 'Grenade',
    name: 'Communal Health Pool',
    manufacturer: 'Maliwan',
    redText: 'Yoink!',
    effect:
      'Greatly increased DoT damage, grenades stick to target until detonation, launches more transfusions on detonation',
    rarity: 'Legendary',
  },
  {
    origin: 'Kitten',
    itemType: 'Assault Rifle',
    name: 'Labyrinthine',
    manufacturer: 'Atlas',
    redText: 'My kingdom is great',
    effect: 'Bullet splits into 4 lasers in a square, increased fire rate & damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Lady Fist',
    itemType: 'Pistol',
    name: 'Liquidation',
    manufacturer: 'Hyperion',
    redText: "It's leverage. It's training. It's consulting. It's business.",
    effect: 'Fires railgun shots with a rev up, going from 25% fire rate to 125% fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Landscaper',
    itemType: 'Shotgun',
    name: 'Shrocket',
    manufacturer: 'Torgue',
    redText: 'TORGUE APPROVES THIS MESSAGE!',
    effect: 'Fires rockets, removes Landscaper effect',
    rarity: 'Legendary',
  },
  {
    origin: 'Lascaux',
    itemType: 'SMG',
    name: 'Raiju',
    manufacturer: 'Dahl',
    redText: 'Charged by the spirits',
    effect: "Always Shock, fires 'spectral' bullets, ADS is high speed burst",
    rarity: 'Legendary',
  },
  {
    origin: 'Law',
    itemType: 'Pistol',
    name: 'Fuse',
    manufacturer: 'Jakobs',
    redText: 'Light the fuse, bitches!',
    effect: "Jakobs 'Torgue' pistol, fires gyrojets as fast as you can pull the trigger",
    rarity: 'Legendary',
  },
  {
    origin: 'Lead Storm',
    itemType: 'Assault Rifle',
    name: 'Quintessence',
    manufacturer: 'Atlas',
    redText: 'There is the most translucent kind which is called by the name of aether.',
    effect: 'Fires homing Magic Missile balls, unlocked elements',
    rarity: 'Seraph',
  },
  {
    origin: 'Leech',
    itemType: 'Grenade',
    name: 'Sapper',
    manufacturer: 'Maliwan',
    redText: 'Technology is the sapper of innocence.',
    effect: 'MIRV, transfusion & singularity in 1 grenade (for max sapping)',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Anarchist',
    itemType: 'Class Mod',
    name: 'Hexblade',
    manufacturer: '',
    redText: '"Oh, I am gonna smack the bitch outta you!"',
    effect: 'Increased gun damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Berserker',
    itemType: 'Class Mod',
    name: 'El Heroe',
    manufacturer: '',
    redText: '"Sonrie, hijo de...!"',
    effect: 'Increases movement speed while in Modo Torreta (to normal)',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Binder',
    itemType: 'Class Mod',
    name: 'Vaultbound',
    manufacturer: '',
    redText: 'The Guardians have no need to serve as jailkeepers, only as sentinels at the walls.',
    effect: 'Increases Phaselock duration',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Cat',
    itemType: 'Class Mod',
    name: 'Arch Sera',
    manufacturer: '',
    redText: 'When the gates open up, the choirs are heard.',
    effect: 'Provides gun damage & team ammo regen',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Catalyst',
    itemType: 'Class Mod',
    name: 'Streamer',
    manufacturer: '',
    redText: '"Um... so, hello... huh... my... twenty thousand subscribers."',
    effect: 'Increased team DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Engineer',
    itemType: 'Class Mod',
    name: 'Assembler',
    manufacturer: '',
    redText: '"Bad guys - zero, Turret - a whole bunch!"',
    effect: 'Increased cooldown rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Gunzerker',
    itemType: 'Class Mod',
    name: 'El Fusil',
    manufacturer: '',
    redText: '"¿Que dijiste de mi pistola?"',
    effect: 'Increased Modo Torreta gun damage & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Hoarder',
    itemType: 'Class Mod',
    name: 'Mariachi',
    manufacturer: '',
    redText: '"¿Puedo matar todo con un solo disparo todavia?"',
    effect: 'Provides team ammo regeneration',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Hunter',
    itemType: 'Class Mod',
    name: 'Mopey',
    manufacturer: '',
    redText: '"An idle mind / Is a very dangerous thing / I think of violence"',
    effect: 'Increased reload speed, movement speed & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Killer',
    itemType: 'Class Mod',
    name: 'Ruthless Legendary Executioner',
    manufacturer: '',
    redText: '"Critical killing / Is an art unto itself / And I am Rembrandt."',
    effect: 'Increased team critical damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Mechromancer',
    itemType: 'Class Mod',
    name: 'Necromancer',
    manufacturer: '',
    redText: "It's totally gonna happen again.",
    effect: 'Decreased action skill cooldown',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Ninja',
    itemType: 'Class Mod',
    name: 'Hokage',
    manufacturer: '',
    redText: '"An execution / Swift, vicious and efficient / And yet, personal."',
    effect: 'Increased melee damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Nurse',
    itemType: 'Class Mod',
    name: 'Opha Superior',
    manufacturer: '',
    redText: "Mother's Embrace",
    effect: 'Provides team health & shield regen',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Pointman',
    itemType: 'Class Mod',
    name: 'Defender',
    manufacturer: '',
    redText: '"I can\'t feel my face. Prob\'ly a good thing."',
    effect: 'Increased health regen & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Psycho',
    itemType: 'Class Mod',
    name: 'Maniac',
    manufacturer: '',
    redText: '"I taste blood... mine AND yours!!" "NIPPLE SALADS!"',
    effect: 'Increased burn damage, magazine size & shield recharge delay',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Ranger',
    itemType: 'Class Mod',
    name: 'Military Regime',
    manufacturer: '',
    redText: '"Ten years of Dahl military experience at your service."',
    effect: 'Increased team shield recharge rate & delay',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Reaper',
    itemType: 'Class Mod',
    name: 'Genocide',
    manufacturer: '',
    redText: '"NEVER STOP THE KILLING!! NEVER!!"',
    effect: 'Increases Bloodlust stack decay',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Roboteer',
    itemType: 'Class Mod',
    name: 'Conjurer',
    manufacturer: '',
    redText: '"Respect the robot!"',
    effect: 'Decreased action skill cooldown & increased melee damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Sickle',
    itemType: 'Class Mod',
    name: 'Eviscerator',
    manufacturer: '',
    redText: '"I\'LL SLICE YOUR EYELIDS SO YOU CAN WATCH THE END!!"',
    effect: 'Increased team melee damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Siren',
    itemType: 'Class Mod',
    name: 'Badass Wraith',
    manufacturer: '',
    redText: '"Anyone need a Siren on their side?"',
    effect: 'Increased reload speed & movement speed',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Sniper',
    itemType: 'Class Mod',
    name: 'Sharpshooter',
    manufacturer: '',
    redText: '"Why does everyone / get all weird about my hands? / Who needs a pinky?"',
    effect: 'Increased sniper rifle gun damage & crit damage, decreased shield capacity',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Soldier',
    itemType: 'Class Mod',
    name: 'Armada',
    manufacturer: '',
    redText: '"YOU get a bullet! And YOU get a bullet! EVERYBODY get a bullet!"',
    effect: 'Changed Legendary COM skill boosts',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Titan',
    itemType: 'Class Mod',
    name: 'La Cucaracha',
    manufacturer: '',
    redText: '"¡Me hiciste dejar de disparar!"',
    effect: 'Increases health regen & gun damage, reduces shield capacity',
    rarity: 'Legendary',
  },
  {
    origin: 'Legendary Torch',
    itemType: 'Class Mod',
    name: 'Cremator',
    manufacturer: '',
    redText: '"I EMBRACE THE FLAME!"',
    effect: 'Increased Incendiary DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Lightning Bolt',
    itemType: 'Grenade',
    name: 'Arcane Bolt',
    manufacturer: 'Maliwan',
    redText: 'Hocus pocus, bitch!',
    effect: 'Throws a magic arrow spike, Fastball style impact',
    rarity: 'Legendary',
  },
  {
    origin: 'Little Evie',
    itemType: 'Pistol',
    name: 'Lynceus',
    manufacturer: 'Atlas',
    redText: 'The only survivor of the 50 sons of Aegyptus',
    effect:
      "Now Vladof, element unlocked, grants a stack of 'Vengeance' on kill. Each stack of Vengeance lasts 30 seconds, and grants increased damage resistance, movement speed, gun damage & fire rate",
    rarity: 'Legendary',
  },
  {
    origin: "Logan's Gun",
    itemType: 'Pistol',
    name: 'Slag Habit',
    manufacturer: 'Maliwan',
    redText: 'This Eridium stuff is the tits!',
    effect: 'Now Maliwan, always slag, fires a bullet that explodes into 2 Slag Novas & 1 large Slag Nova.',
    rarity: 'Legendary',
  },
  {
    origin: 'Longbow',
    itemType: 'Sniper Rifle',
    name: 'Blazing Recurve',
    manufacturer: 'Hyperion',
    redText: 'Set thine foes aflame - with great panache!',
    effect: 'Always fire, fires flaming arrows, increased damage, accuracy, DoT chance & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Love Thumper',
    itemType: 'Shield',
    name: 'Rolan',
    manufacturer: 'Jakobs',
    redText: "That's 180 days of training. Completed.",
    effect: 'Jakobs shield, 0 capacity but increased Roid damage & max health, melee attacks have life leech',
    rarity: 'Legendary',
  },
  {
    origin: 'Lucrative Opportunity',
    itemType: 'Relic',
    name: 'Edgerunner',
    manufacturer: 'Eridian',
    redText: 'Sorry, wish we could go to the moon together.',
    effect: 'Provides a small chance to dodge bullets and reflect them back to attackers. Increased movement speed',
    rarity: 'Legendary',
  },
  {
    origin: 'Lyuda/Lyudmila/White Death',
    itemType: 'Sniper Rifle',
    name: 'Moirai',
    manufacturer: 'Atlas',
    redText: 'The spinner, the allotter and the inevitable.',
    effect: 'Fires 3 bullets per shot with no fixed split, slightly increased damage, +150% crit damage',
    rarity: 'Legendary',
  },
  {
    origin: 'M2828 Thumpson',
    itemType: 'Assault Rifle',
    name: '@Everyone',
    manufacturer: 'Hyperion',
    redText: 'Ping!',
    effect: 'Shots ricochet into 5 explosive bullets with wide spread. Increased fire rate & mag size',
    rarity: 'Legendary',
  },
  {
    origin: 'Madhous!',
    itemType: 'Assault Rifle',
    name: 'RifRaf',
    manufacturer: 'S&S Munitions',
    redText: "I've always had great ideas.",
    effect: 'Ricochets spawn a bunch of lasers',
    rarity: 'Legendary',
  },
  {
    origin: 'Maggie',
    itemType: 'Pistol',
    name: 'High Noon',
    manufacturer: 'Jakobs',
    redText: 'Fan the hammer!',
    effect:
      'One trigger pull fires 25 bullets (or all bullets in mag, whichever is lower), increased damage & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Magic Missile',
    itemType: 'Grenade',
    name: 'Crystalixir',
    manufacturer: 'Maliwan',
    redText: 'The shards hold infernal power',
    effect:
      'Throws a crystal spike that explodes on impact, or sticks to surfaces and detonates, dealing Incendiary Damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Manly Man Shield',
    itemType: 'Shield',
    name: 'Hypnofocused',
    manufacturer: 'Torgue',
    redText: 'Too much of a good thing can make a man vulnerable',
    effect:
      'Grants full immunity to slag but you take 50% increased elemental damage. Adds bonus slag damage to all melee attacks',
    rarity: 'Legendary',
  },
  {
    origin: 'Meteor Shower',
    itemType: 'Grenade',
    name: 'Scattershot',
    manufacturer: 'Torgue',
    redText: "Just to make sure we've covered all our bases...",
    effect: 'Additional MIRV alongside Meteor Shower effect',
    rarity: 'Seraph',
  },
  {
    origin: 'Midnight Star',
    itemType: 'Grenade',
    name: 'Thorns of Cassius',
    manufacturer: 'Torgue',
    redText: 'Gotta hand it to Cassius. This may be all his fault, but he did everything he could to make it right.',
    effect: 'On detonation, summons a bunch of thorns from the ground that deal Corrosive damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Might of the Seraphs',
    itemType: 'Relic',
    name: 'Shaped Glass',
    manufacturer: 'Eridian',
    redText: 'A cost he was willing us to pay.',
    effect: 'Increased melee damage but decreased max HP.',
    rarity: 'Seraph',
  },
  {
    origin: 'Mongol',
    itemType: 'Launcher',
    name: 'Myrmidon',
    manufacturer: 'Atlas',
    redText: 'From ants we were born, our civilisation rises again.',
    effect: 'Fires a rocket that spawns homing spiker projectiles in flight',
    rarity: 'Legendary',
  },
  {
    origin: 'Morningstar',
    itemType: 'Sniper Rifle',
    name: 'Executioner',
    manufacturer: 'Hyperion',
    redText: 'Judge, jury and me.',
    effect:
      'Critical hits grant a stack of "Bounty" that gives +5% critical hit damage, +5% damage, +5% faster fire rate, +5% mag size & +0.1 sniper rifle ammo regen for 25 seconds.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Mouthwash',
    itemType: 'Relic',
    name: 'White Tiger',
    manufacturer: 'Eridian',
    redText: "A white tiger keeps no friends. It's too dangerous.",
    effect: 'Increases movement speed & jump height while your shield is depleted.',
    rarity: 'Legendary',
  },
  {
    origin: "Moxxi's Endowment",
    itemType: 'Relic',
    name: 'Blessing',
    manufacturer: 'Eridian',
    redText: "Let's keep you alive, sugar.",
    effect: 'Increased XP gain & provides health leech',
    rarity: 'Moxxi',
  },
  {
    origin: 'Mysterious Amulet',
    itemType: 'Relic',
    name: 'Friendship Is Magic',
    manufacturer: 'Eridian',
    redText: '',
    effect: 'Increases gun damage, fire rate, reload speed & accuracy for your friends... not you.',
    rarity: 'Effervescent',
  },
  {
    origin: 'Nasty Surprise',
    itemType: 'Grenade',
    name: 'Bombardment',
    manufacturer: 'Hyperion',
    redText: 'We will break down their fortifications!',
    effect: 'Same Nasty Surprise effect, more grenades spawn on impact',
    rarity: 'Legendary',
  },
  {
    origin: 'Neogenator',
    itemType: 'Shield',
    name: 'Unburden',
    manufacturer: 'Anshin',
    redText: 'Sometimes, we just have to let things go.',
    effect: 'Provides increased movement speed & fire rate while active. The lower your shields, the bigger the bonus',
    rarity: 'Legendary',
  },
  {
    origin: 'Nirvana ',
    itemType: 'SMG',
    name: 'Rainbow Connection',
    manufacturer: 'Maliwan',
    redText: "Someday we'll find it. The lovers, the dreamers and me.",
    effect: 'Always Fire, fires rainbow rocks, increased DoT chance & DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Norfleet',
    itemType: 'Launcher',
    name: 'Aftershock',
    manufacturer: 'Torgue',
    redText: "You can't predict an earthquake",
    effect:
      'Now Torgue, always non-elemental, fires 1 rocket that explodes nearby enemies on impact. Increased mag size & damage',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Nukem',
    itemType: 'Launcher',
    name: 'Pyro Lance',
    manufacturer: 'Atlas',
    redText: 'What medicines do not heal, the lance will. What the lance does not heal, fire will.',
    effect: 'Now Atlas, always Fire, fires a fireball',
    rarity: 'Legendary',
  },
  {
    origin: 'O-Negative',
    itemType: 'Grenade',
    name: 'Lazarus Effect',
    manufacturer: 'Maliwan',
    redText: 'Your life force sustains us for eons!',
    effect: 'Spawns more transfusions on detonation',
    rarity: 'Seraph',
  },
  {
    origin: 'Octo',
    itemType: 'Shotgun',
    name: 'Scatter Laser',
    manufacturer: 'Tediore',
    redText: 'An application of laser technology to the shotgun',
    effect: 'Fires 9 lasers in a square pattern, increased fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Ogre ',
    itemType: 'Assault Rifle',
    name: 'Kratos',
    manufacturer: 'Torgue',
    redText: 'If you cannot control your rage, it will consume the entire world.',
    effect:
      'Every 6 seconds, has a 20% chance to go "Berzerk",  increasing projectile count to 6, increased damage & fire rate, 0 ammo cost but continues firing non-stop',
    rarity: 'Legendary',
  },
  {
    origin: 'Omen',
    itemType: 'Shotgun',
    name: 'Half-Life',
    manufacturer: 'Tediore',
    redText: 'Well, it does seem there is something to chaos theory after all, yes?',
    effect:
      'Fires a splatgun projectile that stops in the air and shoots plasma projectiles in a random spread until it explodes and releases 15. Custom explosions',
    rarity: 'Seraph',
  },
  {
    origin: 'Orc',
    itemType: 'SMG',
    name: 'Slurd Wurdz',
    manufacturer: 'S&S Munitions',
    redText: "Moxxi's Tavern is the #1 hotspot around here!",
    effect:
      'Every 6 seconds, has a chance to make you "Drunk", increasing projectile count, DoT damage & DoT chance & decreasing accuracy & fire rate.',
    rarity: 'Legendary',
  },
  {
    origin: 'Order',
    itemType: 'Shield',
    name: 'Payload',
    manufacturer: 'Jakobs',
    redText: "I'm ready to blow!",
    effect: 'Jakobs shield, slow recharge delay, if holding the Law while depleted, melee attacks explode',
    rarity: 'Legendary',
  },
  {
    origin: 'Orphan Maker',
    itemType: 'Shotgun',
    name: 'Culverin',
    manufacturer: 'Jakobs',
    redText: 'BLOW THOSE IMPERIALS TO KINGDOM COME!',
    effect: 'Fires 2 cannonballs with greatly increased damage & knockback, consumes 2 ammo per shot',
    rarity: 'Legendary',
  },
  {
    origin: 'Otto Idol',
    itemType: 'Relic',
    name: 'Transcendence',
    manufacturer: 'Eridian',
    redText: 'I have escaped my suffering.',
    effect:
      'Curse of Frailty: Sets your maximum health to 1 but greatly increases your maximum shield capacity, shield recharge rate & shield recharge delay.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Overcompensator',
    itemType: 'Shotgun',
    name: 'Gambit',
    manufacturer: 'Hyperion',
    redText: 'Unga bunga dude!',
    effect:
      'Part locked (except hybrids), always Fire, Surplus ammo regen effect, fires incendiary explosive rounds, damage & fire rate are increased the more bullets you have in your mag',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Pandemic',
    itemType: 'Grenade',
    name: "Hornet's Nest",
    manufacturer: 'Atlas',
    redText: 'Why did you poke it?!',
    effect: 'On explosion, spawns a corrosive cloud in an area and 30 Hive child projectiles over 5 seconds',
    rarity: 'Legendary',
  },
  {
    origin: 'Patriot',
    itemType: 'Sniper Rifle',
    name: 'Asclepius',
    manufacturer: 'Atlas',
    redText: 'The smaller the mind, the greater the conceit.',
    effect:
      'Greatly reduces your max HP but provides health leech, transfusion on hit, increased damage & critical damage',
    rarity: 'Seraph',
  },
  {
    origin: 'Peak Opener',
    itemType: 'Assault Rifle',
    name: 'Queen Bee',
    manufacturer: 'Torgue',
    redText: 'The matriarch of the jungle hives.',
    effect: 'Fires a rocket that explodes into a singularity, 10 homing spiker shots & 5 Hive rockets.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Pimpernel',
    itemType: 'Sniper Rifle',
    name: 'Lead Sprinkler',
    manufacturer: 'Jakobs',
    redText: 'Splish splash.',
    effect: "Fires 5 explosive projectiles on impact, increased fire rate (similar to BL3's Lead Sprinkler)",
    rarity: 'Legendary',
  },
  {
    origin: 'Pitchfork',
    itemType: 'Sniper Rifle',
    name: 'Hyperspace',
    manufacturer: 'Dahl',
    redText: 'Punch it Chewie!',
    effect: 'Fires a slow bullet that splits into 8 more in a diamond pattern, all shots start slow & accelerate',
    rarity: 'Legendary',
  },
  {
    origin: 'Pocket Rocket',
    itemType: 'Pistol',
    name: 'Menage a Trois',
    manufacturer: 'Torgue',
    redText: 'Get the boys involved!',
    effect: 'Fires a 3 round burst, rolls on any basic Torgue pistol',
    rarity: 'Legendary',
  },
  {
    origin: "Pot O' Gold",
    itemType: 'Shield',
    name: 'Wonka',
    manufacturer: 'Dahl',
    redText: "Come with me and you'll be in a world of pure imagination...",
    effect: 'Taking damage drops a candy. Candy can be picked up for later use',
    rarity: 'Legendary',
  },
  {
    origin: 'Punchee',
    itemType: 'Shield',
    name: 'Vexation',
    manufacturer: 'S&S Munitions',
    redText: "I'm *this* close to losing my absolute shit right now!",
    effect: 'Constantly draining Roid shield, provides passive health regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Pyrophobia',
    itemType: 'Launcher',
    name: 'Meltdown',
    manufacturer: 'Maliwan',
    redText: 'Bathe in natural environmental radiation.',
    effect: 'Always corrosives, fast midair explosions, increased damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Quasar',
    itemType: 'Grenade',
    name: 'Malfunction',
    manufacturer: 'Hyperion',
    redText: 'Quasar, do something!',
    effect: 'Shock grenade that explodes on impact, extra large shock range',
    rarity: 'Legendary',
  },
  {
    origin: 'Rapier',
    itemType: 'Assault Rifle',
    name: 'Blood Pact',
    manufacturer: 'Atlas',
    redText: "Blood doesn't wash away betrayal",
    effect:
      'Curse of the Sanguine: While held, constantly drains your HP. Dealing damage to enemies heals you for 10% of the damage dealt',
    rarity: 'Legendary',
  },
  {
    origin: 'Retainer',
    itemType: 'Shield',
    name: 'Montana',
    manufacturer: 'Dahl',
    redText: 'The world is yours.',
    effect:
      'While My Little Friend is in your hands, you gain increased movement speed, jump height, gun damage, magazine size, fire rate, reload speed, health regeneration and passive shield regeneration. This boost is further increased while you are in Writing Deep.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Retcher',
    itemType: 'Shotgun',
    name: 'Hateseeker',
    manufacturer: 'Tediore',
    redText: 'All must die',
    effect:
      'Fires homing splatgun projectiles that hover on enemies, increased damage, DoT damage & DoT chance, decreased accuracy',
    rarity: 'Seraph',
  },
  {
    origin: 'Rex',
    itemType: 'Pistol',
    name: 'Fillet',
    manufacturer: 'Jakobs',
    redText: 'Gut them like a fish!',
    effect:
      'No barrel, always spawns with a bayonet & no accessory, 0 bullets in the mag, 10,000 shot cost (to stop potential shooting), greatly increased melee damage, provides life leech',
    rarity: 'Legendary',
  },
  {
    origin: 'Roaster',
    itemType: 'Launcher',
    name: 'Clusta',
    manufacturer: 'S&S Munitions',
    redText: 'Bang-bang leads to smash-smash!',
    effect: 'Fires mini grenades, increased projectile count',
    rarity: 'Legendary',
  },
  {
    origin: 'RokSalt',
    itemType: 'Shotgun',
    name: 'ByrdShot',
    manufacturer: 'S&S Munitions',
    redText: "Huntin' some pretty fuckin' big birds.",
    effect: 'Fires spiker shots',
    rarity: 'Legendary',
  },
  {
    origin: 'Rolling Thunder',
    itemType: 'Grenade',
    name: 'Hopscotch',
    manufacturer: 'Torgue',
    redText:
      "I said a hip-hop, the hippie, the hippie; To the hip, hip-hop and you don't stop the rockin'; To the bang-bang boogie, say up jump the boogie; To the rhythm of the boogie, the beat",
    effect: 'Rolling Thunder effect, on explosion spawns a MIRV, transfusion & singularity',
    rarity: 'Legendary',
  },
  {
    origin: 'Rough Rider',
    itemType: 'Shield',
    name: "Mr Torgue's Back Muscles",
    manufacturer: 'Torgue',
    redText: "MY BACK MUSCLES ARE SO RIPPED, YOU DON'T EVEN KNOW!",
    effect: 'Increased damage resistance & maximum health, 0 shield capacity',
    rarity: 'Legendary',
  },
  {
    origin: 'Rubi',
    itemType: 'Pistol',
    name: 'Unicorn',
    manufacturer: 'Maliwan',
    redText: 'Little dreams come true.',
    effect: 'Fires unicorns, immune to being slagged, 100% Slag chance, always Slag',
    rarity: 'Moxxi',
  },
  {
    origin: 'Sand Hawk',
    itemType: 'SMG',
    name: 'Buzzwords',
    manufacturer: 'Hyperion',
    redText: 'Profitability! Synergy! Adaptation! Enterprising! MONEY!',
    effect: 'Now Hyperion, fires a shock beam',
    rarity: 'Legendary',
  },
  {
    origin: 'Sawbar',
    itemType: 'Assault Rifle',
    name: 'Flashover',
    manufacturer: 'S&S Munitions',
    redText: 'Always keep the fire burning',
    effect: 'Fires fireballs, increased mag size, fire rate, damage, DoT chance and DoT damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Scorpio',
    itemType: 'Assault Rifle',
    name: 'Vault Key',
    manufacturer: 'Dahl',
    redText: 'The real Vault Key is the friends we made along the way.',
    effect:
      'Fires plasma caster projectiles, deals non-elemental & explosive damage, minigun barrel, slightly increased damage, slightly larger mag size, burst fires all bullets in mag but slightly faster fire rate (5%), always spawns with no accessory (other than hybrid) and non-elemental',
    rarity: 'Legendary',
  },
  {
    origin: 'Seeker',
    itemType: 'Assault Rifle',
    name: 'Infraready',
    manufacturer: 'Torgue',
    redText: 'THE ONLY THING TORGUE LOVES MORE THAN EXPLOSIONS IS MODERN TECHNOLOGY... JUST KIDDING! EXPLOOOOOOOSIONS!',
    effect: 'Fires 3 homing rockets, slightly decreased fire rate',
    rarity: 'Seraph',
  },
  {
    origin: 'Seraphim',
    itemType: 'Assault Rifle',
    name: 'Tetramid',
    manufacturer: 'Dahl',
    redText: 'Great things come in 3s',
    effect: 'Fires 3 shots in a triangle, decreased accuracy but increased damage, DoT damage & DoT chance',
    rarity: 'Seraph',
  },
  {
    origin: 'Shadow of the Seraphs',
    itemType: 'Relic',
    name: 'Pinpoint',
    manufacturer: 'Eridian',
    redText: 'Put it right between the eyes.',
    effect: 'Increases critical damage but decreases base gun damage',
    rarity: 'Seraph',
  },
  {
    origin: 'Sham',
    itemType: 'Shield',
    name: 'Impulse',
    manufacturer: 'Hyperion',
    redText: 'Forget the world! You and me - right now!',
    effect: 'Now a Hyperion Amp shield, heals you when dealing damage',
    rarity: 'Moxxi',
  },
  {
    origin: "Sheriff's Badge",
    itemType: 'Relic',
    name: 'Wild Bill',
    manufacturer: 'Eridian',
    redText: 'Harness mules and oxen, but give a horse a chance to run.',
    effect: 'Increases pistol damage, pistol critical hit damage, pistol ricochets & pistol projectile count.',
    rarity: 'Legendary',
  },
  {
    origin: 'Shotgun 1340',
    itemType: 'Shotgun',
    name: 'R3FL3X0R-1340',
    manufacturer: 'Hyperion',
    redText: 'BEAM_OUTPUT = TRUE; TALKING_MODULE = FALSE',
    effect: 'Fires lasers, fast fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Shredifier',
    itemType: 'Assault Rifle',
    name: 'Maelstrom',
    manufacturer: 'Atlas',
    redText: 'To defy me is to defy the power of the earth itself!',
    effect: 'Greatly increased fire rate, increased damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Skullmasher',
    itemType: 'Sniper Rifle',
    name: 'Blackjack',
    manufacturer: 'Jakobs',
    redText: "It's not about the cards you're dealt, but how you play the hand.",
    effect:
      'Fires 7 bullets per shot, 3 bullets in mag, 3 round burst,  increased reload speed & fire rate, increased critical hit damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Slagga',
    itemType: 'SMG',
    name: 'Double Anarchy',
    manufacturer: 'S&S Munitions',
    redText: 'A Double Anarchy is, legitimately, the most powerful weapon in the game.',
    effect: 'Fires 4 bullets, decreased accuracy, increased fire rate & damage, unlocked elements',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Axton',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Gaige',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Krieg',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Maya',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Team Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Salvador',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: 'Slayer of Terra Zer0',
    itemType: 'Class Mod',
    name: "Terra's Guardian",
    manufacturer: '',
    redText: '',
    effect: 'Increased Incendiary DoT damage, DoT chance & max health',
    rarity: 'Legendary',
  },
  {
    origin: "Sledge's Shotgun",
    itemType: 'Shotgun',
    name: 'Tantrum',
    manufacturer: 'S&S Munitions',
    redText: 'I WANT IT AND I WANT IT NOW!',
    effect: 'No longer bursts, fast fire rate, 1 ammo per shot, inaccurate',
    rarity: 'Legendary',
  },
  {
    origin: 'Sloth',
    itemType: 'Sniper Rifle',
    name: 'Adaptation',
    manufacturer: 'Dahl',
    redText: 'Imitation is the sincerest form of warfare.',
    effect:
      "Hyperion body, barrel & skin on Dahl sniper, always non-elemental, 1 shot burst when scoped, fires Hyperion turret shots, increased crit 'radius' (can crit on body shots), increased base damage",
    rarity: 'Legendary',
  },
  {
    origin: 'Slow Hand',
    itemType: 'Shotgun',
    name: 'B-Rex',
    manufacturer: 'Torgue',
    redText: "I'M NOT A DAMN CHEATER!",
    effect: 'Now Torgue, fires mortars for 2 ammo, increased based damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Sponge',
    itemType: 'Shield',
    name: 'Damper',
    manufacturer: 'Atlas',
    redText: "You're a dampener of dreams.",
    effect: 'Absorbs 100% of bullets, but they deal 50% regular damage.',
    rarity: 'Seraph',
  },
  {
    origin: 'Stalker',
    itemType: 'Pistol',
    name: 'Barrage',
    manufacturer: 'Torgue',
    redText: 'TORGUE? EXPLOSIONS! EXPLOSIONS? TORGUE!',
    effect:
      "Now Torgue (using Stalker body), element unlocked (yeah, it's crazy), rapid fire Torgue pistol, increased mag size & damage",
    rarity: 'Pearlescent',
  },
  {
    origin: 'Stinger',
    itemType: 'Pistol',
    name: 'Cyber Blaster',
    manufacturer: 'Atlas',
    redText: 'A working model from the Decker Use-Net.',
    effect: 'Fires lasers, 100% chance to penetrate shields, increased critical damage',
    rarity: 'Seraph',
  },
  {
    origin: 'Stinkpot',
    itemType: 'Assault Rifle',
    name: 'Jigowatt',
    manufacturer: 'Jakobs',
    redText: '1.21 jigo-who-the-what-nows?!',
    effect: 'Non-elemental, fires a slow splatgun projectile that explodes on impact',
    rarity: 'Legendary',
  },
  {
    origin: 'Stomper',
    itemType: 'Assault Rifle',
    name: 'Apollo',
    manufacturer: 'Atlas',
    redText: 'The sun rises for all, but not all see its light.',
    effect: 'Always elemental, now Vladof, fires a laser & lightning bolt, increased damage & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Storm',
    itemType: 'Sniper Rifle',
    name: 'EMF',
    manufacturer: 'Maliwan',
    redText: 'Truly shocking stuff, I know!',
    effect: 'Normal Storm firing mode, spawns Storm Front child grenades on impact',
    rarity: 'Legendary',
  },
  {
    origin: 'Storm Front',
    itemType: 'Grenade',
    name: 'Faraday',
    manufacturer: 'Atlas',
    redText: 'Like a rat in an electrified cage',
    effect: 'Greatly increased child projectile count but wider spread',
    rarity: 'Legendary',
  },
  {
    origin: 'Striker',
    itemType: 'Shotgun',
    name: 'Headshot',
    manufacturer: 'Jakobs',
    redText: 'SHOOT ME IN THE FACE!',
    effect: 'Greatly increased damage & critical damage, can spawn with any barrel, always 2 shots in mag',
    rarity: 'Legendary',
  },
  {
    origin: 'SWORDSPLOSION',
    itemType: 'Shotgun',
    name: 'Cloud Kill',
    manufacturer: 'Hyperion',
    redText: "I can't die like this... not when I'm so close...",
    effect: 'Now Hyperion, always Corrosive, fires a splatgun projectile that spawns a toxic cloud on impact.',
    rarity: 'Legendary',
  },
  {
    origin: 'Tattler',
    itemType: 'SMG',
    name: 'Ghoulish Gouger',
    manufacturer: 'S&S Munitions',
    redText: 'Long-dead prisoners seek their zealous revenge...',
    effect: 'Fires invisible bullets that deal melee damage, damage is changed based on melee skills & relics',
    rarity: 'Seraph',
  },
  {
    origin: 'Teapot',
    itemType: 'Pistol',
    name: 'Contagion',
    manufacturer: 'Dahl',
    redText: "Tamiflu ain't gonna save you this time...",
    effect: 'Always Corrosive, fires splatgun balls, increased damage, DoT chance & DoT damage, decreased mag size',
    rarity: 'Legendary',
  },
  {
    origin: 'Teeth of Terramorphous',
    itemType: 'Shotgun',
    name: 'Anubis',
    manufacturer: 'S&S Munitions',
    redText: 'The God of Death...all grown up.',
    effect: 'Fires 5 grenades per shot, increased damage & fire rate',
    rarity: 'Legendary',
  },
  {
    origin: 'Thunderball Fists',
    itemType: 'Pistol',
    name: 'Vortex',
    manufacturer: 'Maliwan',
    redText: 'You can only coax someone into the vortex from within the vortex',
    effect: 'Spawns a singularity on impact, increased damage, DoT chance & damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Tidal Wave',
    itemType: 'Shotgun',
    name: 'Grand Slam',
    manufacturer: 'Jakobs',
    redText: "It's our game - the Pandoran game.",
    effect: 'Fires 100 pellets with greatly reduced damage but greatly increased knockback. 1 ammo per mag',
    rarity: 'Legendary',
  },
  {
    origin: 'Tinderbox',
    itemType: 'Pistol',
    name: 'SOS Flare',
    manufacturer: 'S&S Munitions',
    redText: 'Who needs help?',
    effect: 'On ricochet (or after 0.75s), splits into 8 arcing projectiles',
    rarity: 'Legendary',
  },
  {
    origin: 'Toothpick',
    itemType: 'Assault Rifle',
    name: 'My Little Friend',
    manufacturer: 'Dahl',
    redText: 'Hello!',
    effect:
      'Unlocked elements, fires 2 bullets per 2 ammo, while Montana is equipped, you gain increased movement speed, jump height, gun damage, magazine size, fire rate, reload speed, health regeneration and passive shield regeneration. This boost is further increased while you are in Writing Deep.',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Transformer',
    itemType: 'Shield',
    name: 'Transistor',
    manufacturer: 'Atlas',
    redText: 'Keeping the charge!',
    effect: 'All status effect damage charges shield',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Trespasser',
    itemType: 'Sniper Rifle',
    name: 'Concentration',
    manufacturer: 'Jakobs',
    redText: 'Just focus...',
    effect:
      'Scoping in adds 1 bullet to the mag, zoomed shots fire all bullets in mag, damage scaled based on remaining bullets in mag.',
    rarity: 'Legendary',
  },
  {
    origin: 'Triquetra',
    itemType: 'Shotgun',
    name: 'Sovereign',
    manufacturer: 'Jakobs',
    redText: 'Your king demands it!',
    effect: 'While scoped, increased movement speed for bullets remaining in mag',
    rarity: 'Legendary',
  },
  {
    origin: 'Tunguska',
    itemType: 'Launcher',
    name: '4th of July',
    manufacturer: 'Torgue',
    redText: 'God bless America!',
    effect: 'Fires a rocket that explodes into fireworks on impact',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Twister ',
    itemType: 'Shotgun',
    name: 'retsiwT',
    manufacturer: 'Jakobs',
    redText: '.nur eht no elbuort gnittuP',
    effect: 'Upside down Twister, deals adaptive damage (Fire on flesh, Shock on shields, Corrosive on Armour)',
    rarity: 'Legendary',
  },
  {
    origin: 'Unforgiven',
    itemType: 'Pistol',
    name: 'Duality',
    manufacturer: 'Jakobs',
    redText: 'The question becomes whether or not to fire, not where to aim.',
    effect:
      'Now a Jakobs shotgun, fires a spread while unscoped, scoping in reduces the pellet count to 1 but increases the damage by 1,000%',
    rarity: 'Legendary',
  },
  {
    origin: 'Unicornsplosion',
    itemType: 'Shotgun',
    name: 'P5YCH0-B34M3R',
    manufacturer: 'S&S Munitions',
    redText: 'M3LT 4LL TH31R F4C35!',
    effect: 'Now a Bandit AR, fires a laser beam that deals explosive damage on impact',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Unkempt Harold',
    itemType: 'Pistol',
    name: 'Exclusion Zone',
    manufacturer: 'Torgue',
    redText: 'He who enters will not return.',
    effect:
      'Fired bullet splits into wavy bullets over time, 6 ammo per shot, lower fire rate, slightly lower damage, main bullet explodes like mini-nuke, no added AoE',
    rarity: 'Legendary',
  },
  {
    origin: 'Vault Hunter Relic',
    itemType: 'Relic',
    name: "Vault Hunter's Knowledge",
    manufacturer: 'Eridian',
    redText: '',
    effect: 'Increases rare loot chance & XP gain',
    rarity: 'Legendary',
  },
  {
    origin: 'Vertias',
    itemType: 'Pistol',
    name: 'Injector',
    manufacturer: 'Atlas',
    redText: 'How else do we mod Borderlands 2?',
    effect:
      'Fires laser blasts, +25% DoT chance and +75% DoT damage for every Injector or Applicator equipped in the party.',
    rarity: 'Legendary',
  },
  {
    origin: 'Veruc',
    itemType: 'Assault Rifle',
    name: 'Adobois',
    manufacturer: 'Dahl',
    redText: 'Ang isang tatsulok ay may tatlong panig',
    effect: 'Spinigun barrel, fires 3 bullets per shot in fixed pattern, increased weapon damage, mag size & accuracy ',
    rarity: 'Moxxi',
  },
  {
    origin: 'Volcano',
    itemType: 'Sniper Rifle',
    name: 'Proton Flare',
    manufacturer: 'Maliwan',
    redText: 'For my part I know nothing with any certainty but teh sight of the stars makes me dream.',
    effect:
      'Fires a single bullet that splits into a large array of flaming Etech projectiles, increased damage, fire rate & mag size ',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Wanderlust ',
    itemType: 'Pistol',
    name: 'Prism',
    manufacturer: 'S&S Munitions',
    redText: "Bad rainbows go to prism...it's a light sentence, but it gives them time to reflect.",
    effect:
      'Now Bandit, always Slag, shots deal all damage types on impact (slag normal shot, fire, shock, corrosive & explosive explosions)',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Whiskey Tango Foxtrot',
    itemType: 'Shield',
    name: 'Celebration',
    manufacturer: 'Dahl',
    redText: "Let's get this party started!",
    effect:
      'When damaged, has a chance to drop a Party Popper that spawns 5 volleys of fireworks. Picking up the Party Popper grants Movement Speed',
    rarity: 'Legendary',
  },
  {
    origin: 'Winter is Over',
    itemType: 'Relic',
    name: 'Elementalist',
    manufacturer: 'Eridian',
    redText: '',
    effect: 'Increases all elemental damage and provides elemental damage resistance.',
    rarity: 'Legendary',
  },
  {
    origin: 'World Burn',
    itemType: 'Launcher',
    name: 'Extinction',
    manufacturer: 'Torgue',
    redText: "Ah, so that's where the dinosaurs went!",
    effect: 'Always Fire, fires a large flaming meteor',
    rarity: 'Legendary',
  },
  {
    origin: 'Yellow Jacket',
    itemType: 'SMG',
    name: 'Plasma Coil',
    manufacturer: 'Hyperion',
    redText: 'Harness the 4th state of matter.',
    effect:
      'Fires plasma caster projectiles that deal shock & fire damage on impact, increased mag size, damage, DoT damage & DoT chance',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Testing Fire Infinity',
    itemType: 'Pistol',
    name: 'Grindell',
    manufacturer: 'Maliwan',
    redText:
      'The M6 is one of those rare systems that simultaneously boosts morale, degrades the fighting spirit of the enemy and actually performs admirably as a weapon.',
    effect:
      'Now Maliwan, always elemental, fires 16 lasers in a very close cluster (for a super large laser), consumes 5 ammo per shot, 1% chance to apply a status effect and 2 DoT damage (no DoTs)',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Fire Drill',
    itemType: 'Pistol',
    name: 'Heaven Piercer',
    manufacturer: 'Jakobs',
    redText: 'Who the hell do you think we are?!',
    effect: 'Infinite ammo, fires a short-range spiralling projectile',
    rarity: 'Legendary',
  },
  {
    origin: 'Assassin Cyan Skin A',
    itemType: 'Skin',
    name: 'Dynamighty',
    manufacturer: 'Jakobs',
    redText: "Oh, I like to throw my dynamite, throw it real far. Where will it land? Well, I really don't care.",
    effect: 'Throw a stick of dynamite as your enemies, increased base damage',
    rarity: 'Legendary',
  },
  {
    origin: 'Assassin Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Zer0)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Mercenary Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Sal)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Mechromancer Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Gaige)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Psycho Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Krieg)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Siren Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Maya)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Soldier Red Skin F',
    itemType: 'Skin',
    name: 'Slayer of Seraphs (Axton)',
    manufacturer: 'Eridian',
    redText: 'Claim their might as your own...',
    effect: 'Increased damage, status effect resistance & provides ammo regeneration',
    rarity: 'Seraph',
  },
  {
    origin: 'Assassin Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Zer0)',
    manufacturer: 'Hyperion',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Mercenary Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Sal)',
    manufacturer: 'Jakobs',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Mechromancer Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Gaige)',
    manufacturer: 'Atlas',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Psycho Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Krieg)',
    manufacturer: 'S&S Munitions',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Siren Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Maya)',
    manufacturer: 'Maliwan',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Soldier Cyan Skin H',
    itemType: 'Skin',
    name: 'Slayer of Craw (Axton)',
    manufacturer: 'Dahl',
    redText: 'Vincible!',
    effect: 'Increased Shock damage, Shock status chance & shield capacity',
    rarity: 'Pearlescent',
  },
  {
    origin: 'Assassin Cyan Skin F',
    itemType: 'Skin',
    name: 'Exiled Akatsuki',
    manufacturer: 'Hyperion',
    redText: '"My sword is so sharp / I wonder how many men / I could cleave at once."',
    effect: 'Increased melee damage, sniper damage and critical hit damage. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
  {
    origin: 'Mercenary Cyan Skin F',
    itemType: 'Skin',
    name: 'El Chupacabra',
    manufacturer: 'Jakobs',
    redText: '"VAMANOS, PUTAS!"',
    effect: 'Increased melee damage, movement speed & reload speed. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
  {
    origin: 'Mechromancer Cyan Skin F',
    itemType: 'Skin',
    name: 'Princess of Darkness',
    manufacturer: 'Atlas',
    redText: '"To hell with the First Law"',
    effect: 'Increased melee damage, fire damage & air movement speed. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
  {
    origin: 'Psycho Cyan Skin F',
    itemType: 'Skin',
    name: 'Melee God',
    manufacturer: 'S&S Munitions',
    redText: '"I\'m the conductor of the poop train!"',
    effect: 'Increased melee damage, explosive damage & max health. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
  {
    origin: 'Siren Cyan Skin F',
    itemType: 'Skin',
    name: 'Melee Angel',
    manufacturer: 'Maliwan',
    redText: '"I punch him!"',
    effect: 'Increased melee damage, max health & provides passive health regen. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
  {
    origin: 'Soldier Cyan Skin F',
    itemType: 'Skin',
    name: 'Military Specialist',
    manufacturer: 'Dahl',
    redText: '"Boom-Shaka-Laka!"',
    effect: 'Increased burst count, weapon damage, fire rate & explosive damage. Provides +7 bonuses',
    rarity: 'Effervescent',
  },
] as const;

export const ITEM_TYPES = Array.from(new Set(ITEMS.map((item) => item.itemType)));
export const ITEM_MANUFACTURERS = Array.from(new Set(ITEMS.map((item) => item.manufacturer)));
export const ITEM_RARITIES = Array.from(new Set(ITEMS.map((item) => item.rarity)));

export const ITEM_CATEGORY_MAP = {
  shield: 'shields',
  grenade: 'grenades',
  relic: 'relics',
  skin: 'skins',
  'class mod': 'class mods',
};

export const ITEM_CATEGORIES = ['weapons', ...Object.values(ITEM_CATEGORY_MAP)];
